--SQL_S1_26
--CSKMITL_2565

DROP TABLE Member;
DROP TABLE MemberType;
DROP TABLE BILL;
DROP TABLE PRODUCT;
DROP TABLE OrderList;
DROP TABLE PRODUCTTYPE


CREATE TABLE MemberType(
TypeID int NOT NULL ,
TypeName VARCHAR(6) NOT NULL ,
DiscountPrice Float,
PRIMARY KEY(TypeID)
);


CREATE TABLE Member(
memberID CHAR(4) NOT NULL ,
FNAME VARCHAR(16) NOT NULL,
LNAME VARCHAR(16) NOT NULL,
Age int ,
Birthdate DATE,
DiscountPrice int,
TypeID int ,
PRIMARY KEY(memberID),
FOREIGN KEY(TypeID) REFERENCES MemberType(TypeID)
);


CREATE TABLE PRODUCTTYPE(
Tpye int NOT NULL,
TpyeName CHAR(20),
PRIMARY KEY(Tpye)
);


CREATE TABLE PRODUCT(
PRODUCT_ID CHAR(5),
PROUDUCTPICE float(126),
PRODUCTNAME CHAR(20), 
Tpye int NOT NULL,
PRIMARY KEY(PRODUCT_ID),
FOREIGN KEY(Tpye) REFERENCES PRODUCTTYPE(Tpye)
);


CREATE TABLE OrderList
(
Sequence int,
BILL_ID CHAR(10) NOT NULL,
PROUDUCTPICE int,
PRODUCT_ID CHAR(16) NOT NULL,
PRIMARY KEY(Sequence,BILL_ID),
FOREIGN KEY(BILL_ID) REFERENCES BILL(BILL_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

